version: '3.7'

services:
  waha:
    image: devlikeapro/waha:arm
    container_name: waha
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - WAHA_BACKEND=baileys
      - WAHA_SECRET=RvW9v9JH2fH3LgwKu2NUMXFfgu9HLued6Gp
      - WAHA_LOG_LEVEL=debug
    volumes:
      - ./waha_data:/app/sessions
